# Generated by Django 4.2.13 on 2024-05-29 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YellowCab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VendorID', models.IntegerField()),
                ('tpep_pickup_datetime', models.DateTimeField()),
                ('tpep_dropoff_datetime', models.DateTimeField()),
                ('passenger_count', models.IntegerField()),
                ('trip_distance', models.FloatField()),
                ('RatecodeID', models.IntegerField()),
                ('store_and_fwd_flag', models.CharField(max_length=1)),
                ('PULocationID', models.IntegerField()),
                ('DOLocationID', models.IntegerField()),
                ('payment_type', models.IntegerField()),
                ('fare_amount', models.FloatField()),
                ('extra', models.FloatField()),
                ('mta_tax', models.FloatField()),
                ('tip_amount', models.FloatField()),
                ('tolls_amount', models.FloatField()),
                ('improvement_surcharge', models.FloatField()),
                ('total_amount', models.FloatField()),
                ('congestion_surcharge', models.FloatField()),
            ],
        ),
    ]
